### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by InvincibleRMC**
# Pull Request

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [ ] Feature
- [ ] Bug Fix
- [ ] Optimization
- [x] Documentation Update

## Description

I think this is unnecessary

## Related Tickets & Documents

- Related Issue #
#14 
- Closes #

### CODE REVIEW

**Comment by benjaminwp18** [comment]
Is this no longer true?

**Comment by InvincibleRMC** [comment]
I mean it is but, I think it is not necessary to mention.

**Comment by InvincibleRMC** [comment]
I think our docs should as simple as possible while being informative and I feel this is just fluff and obvoius.

**Comment by InvincibleRMC** [comment]
Especially since ROS will let you know if you haven't removed it

**Pull request closed without merging**
